### ISSUE TITLE
I am having troubel loading the trbuchets.

### ISSUE THREAD

**Issue by stretch07** [Carbon-Trebuchet/trebuchetOS#1]

**Comment by ctrlyy** [comment]
just uhhh fart on the disc drive and will work me promise

**Comment by ctrlyy** [comment]
no but seriously no devlopnet yet, just fart

**Comment by its-pablo** [comment]
Understand. Fart and trbuchet. Fart and trbuchet. OS will. Work when I fart on the. Thank you for this valuable informationing.

g
